### ISSUE TITLE
Getting Error: Prune mode is incompatible with -txindex. on launching omnicore

### ISSUE THREAD

**Issue by Mith01** [OmniLayer/omnicore#1235]
I have just installed the new omnicore version 0.10.0 ( https://www.omnilayer.org/download.html ) and launching the app shows the the error below:

> Error: Prune mode is incompatible with -txindex.

I had the previous version 0.9.0 and it was running perfectly fine as testnet wallet. Had a Mac OS upgrade and the Omnicore stopped working as it kept showing N/A for addresses and Invalid Transaction for every transaction i made. Uninstalled the previous version completely and downloaded the 0.10.0 version  ( https://www.omnilayer.org/download.html) and installed. Upon launching it getting 

> Error: Prune mode is incompatible with -txindex. on launching omnicore

Refer to the error here :

![image](https://user-images.githubusercontent.com/86885285/124359115-1a365a80-dc56-11eb-9093-80fe2a2a81ca.png)

Machine details : Macbook Pro ( macOS big sur version 11.4 )

Any suggestions to fix this error ?

**Comment by achamely** [comment]
@Mith01 You can not run prune mode and txindex at the same time. As the message states, they are incompatible. The reason is that omni core needs txindex enabled in order to access / parse the omni data out of the bitcoin transactions (both current and previous historical txs).
Prune mode discards old txs which prevents omni core from having access to the data it needs to operate.

You need to disable prune mode, make sure txindex is enabled in your config file and restart omni core one time with -reindex

Also make sure you upgrade to the latest release, 0.11
