### ISSUE TITLE
Does anyone know that bitcoin core and Omni core can be installed together

### ISSUE THREAD

**Issue by aipap** [OmniLayer/omnicore#1250]

**Comment by aipap** [comment]
I have a website that uses BTC and USDT, do I need to install both Bitcoin core and OMni core？

**Comment by achamely** [comment]
Omni Core is based on Bitcoin Core and provides all the same functionality it does. 
You can either user Omni Core in place of Bitcoin core to support both otherwise it is possible to run both Omni Core and Bitcoin core side by side by side however you would need two different data directories with their own copies of the blockchain data and the machine specs would have to be very very beefy to support both clients simultaneously. Basically like running two versions of Bitcoin core on same machine
