### ISSUE TITLE
I have "invalid transaction" in omnicore explorer but the transaction was proceed in the BTC network as normal transaction ...what do i need to do ?

### ISSUE THREAD

**Issue by pjduvivier** [OmniLayer/omnicore#1253]
Hi

I use omni_sendall to process transaction between BTC addresses - OK

But all my transactions appears as "invalid transaction" in the omnicore channels :

For example :  

{
  "block": 731858, 
  "blockhash": "00000000000000000008d9fc99b8501b595be32ea4464eddcc599f81c1a6dc89", 
  "blocktime": 1649952143, 
  "confirmations": 231, 
  "ecosystem": "main", 
  "fee": "0.00000276", 
  "invalidreason": "Sender has no tokens to send", 
  "ismine": false, 
  "positioninblock": 1999, 
  "referenceaddress": "3QP4zCfqaDPZK1ZMNXmHVpaLpQcz36zE76", 
  "sendingaddress": "3G7UWVUr5yrfgn8vSekviX8sHcfZBUGSLh", 
  "subsends": [], 
  "txid": "ed8030df5b31b345134257564af34cd788d02857803a080abc13cf45f700e8a6", 
  "type": "Send All", 
  "type_int": 4, 
  "valid": false, 
  "version": 0
}

Blockexplorer for BTC is fine : 

https://www.blockchain.com/btc/tx/ed8030df5b31b345134257564af34cd788d02857803a080abc13cf45f700e8a6

How i can send also "valid transaction" in the logic of omnicore ? what command i need to use ? 

The command is sent in CLI mode and not any RPC attempt.

**Comment by achamely** [comment]
@pjduvivier  any command that starts with `omni_` will only affect/be applicable to Omni Protocol tokens.  As your sending address, 3G7UWVUr5yrfgn8vSekviX8sHcfZBUGSLh, has no Omni protocol tokens the attempt to create an Omni Send All transaction fails, because there are no Omni protocol tokens to send.  If you are trying to send your BTC you can use the normal Bitcoin Core RPC commands. Omni Core is built on Bitcoin Core so all the normal regular Bitcoin RPC's (those that **do not** start with `omni_` are applicable and work as expected.

**Comment by pjduvivier** [comment]
@achamely understood thanks for the reply. I will test.
