### ISSUE TITLE
confirmed TMSC/TMSAFE3 DEx exchange still showing unconfirmed in UI

### ISSUE THREAD

**Issue by CraigSellars** [OmniLayer/omnicore#154]
process followed:
1. made sell offer of TMSAFE3
2. checked “trade history” panel
2a. pending tx is shown
2b. double click on item and see **pending tx** message
3. transaction confirms
3a. sell offer shows up on “trade mastercoin/smart properties” sell side table
4. item in “trade history” still shows date: unconfirmed, status: Pending
4a. double click on item and see full non-pending info (including confirmations: 2)
5. item on history still thinks it’s unconfirmed
![screen shot 2015-07-29 at 2 10 27 pm](https://cloud.githubusercontent.com/assets/6528096/8969984/9d8ce5aa-35fb-11e5-96ba-a082f7964b96.png)

**Comment by zathras-crypto** [comment]
Thanks for the report - I was sure I'd squashed this particular bug but appears not - it'll be down to UI signalling & I'll take another run through it...

**Comment by dexX7** [comment]
I'm not able to reproduce this issue in regtest mode. Might be noted though that all involved addresses (i.e. the one, which creates the properties to trade with, and the ones trading) are in the wallet.

**Comment by dexX7** [comment]
I'm currently testing the feature activation PR in regtest mode, and the MetaDEx is currently not yet activated. The UI blocked main ecosystem trades, but I sent one via RPC, which went through.

The trade is nevertheless invalid (because not yet activated), and the transaction is now shown as unconfirmed, and it doesn't change the status after mining blocks.

**Comment by zathras-crypto** [comment]
> I'm not able to reproduce this issue in regtest mode. Might be noted though that all involved addresses (i.e. the one, which creates the properties to trade with, and the ones trading) are in the wallet.

I also struggled to replicate on testnet, but am about to try on mainnet.  @CraigSellars is this reproducible?  If yes, let's enable wallet cache debugging and see what's going on:
1) Delete omnicore.log
2) Start omnicore with the --omnidebug=walletcache parameter
3) Reproduce the scenario you describe
4) Email me your omnicore.log (compress if needed if too big for attachment limits or dropbox it or something)

> The UI blocked main ecosystem trades

Yeah, the UI will block it until the feature is activated due to the check against ```IsTransactionTypeAllowed``` but trading on test eco properties should be allowed with the change you mentioned here https://github.com/zathras-crypto/omnicore/commit/13980bbd03a9f66a89d13bc8ad4d27c8735d43f1#commitcomment-12488413

> The trade is nevertheless invalid (because not yet activated), and the transaction is now shown as unconfirmed, and it doesn't change the status after mining blocks.

This makes complete sense to me (though needs to be fixed) - basically the wallet cache only notifies the UI of changes if there is a change to the tally involving a wallet address (eg funds moving from available to reserved for example) - since a transaction that's invalid inherently does not modify any state related to the wallet, the cache detects no changes and does not notify the UI of an update.  I'll look at how to address this but sadly it doesn't explain what @CraigSellars reported as that trade was valid.

**Comment by zathras-crypto** [comment]
Note I traded against @CraigSellars trade on mainnet but didn't see the issue either.

I'm a bit in the dark about how this could happen now, in a nutshell once the trade confirmed the wallet cache should have detected a shift in funds from available to reserved and notified the UI of an update.

Since Craig noted:
3. transaction confirms
3a. sell offer shows up on “trade mastercoin/smart properties” sell side table

The only way for this to occur is that the wallet cache detected no changes to wallet addresses, and thus signalled a generic state change (which results in a ```refreshOmniState``` signal which would update non-wallet stuff like trade listings instead of a ```refreshOmniBalances``` signal which would update balances and history).

I think since we're struggling to reproduce the best thing to do is ask @CraigSellars if he can reproduce, and get a debugged wallet cache log as mentioned in a prior comment.

**Comment by dexX7** [comment]
Was anyone able to reproduce the issue?
