### ISSUE TITLE
Request: Unconfirmed transactions are processed and applied to balances

### ISSUE THREAD

**Issue by zathras-crypto** [OmniLayer/omnicore#211]
Due to some excellent work from @dexX7 we now have unconfirmed *transaction* support in the next release (0.0.10) of Omni Core.  

This means (assuming the transaction is in the mempool) we can query a transaction hash before it has confirmed and decode it, and thus provide data about the Omni transaction (excluding validity).

There is a request to support unconfirmed balances in OmniChest's API - in a nutshell if I can:

> http://omnichest.info/requeststat.aspx?stat=balance&prop=1&address=1BitcoinAddress
can return something like
{
  confirmed: 8.7
  unconfirmed: -5
}
can you do that? :)

Now since OmniChest is moving more and more towards just being a scraper for Omni Core to ensure all data is from the reference client, there seems little point in adding that logic to 'Chest.  On the flip side it's not like we can just run an unconfirmed transaction through state processing to add the capability to Core either.

So, couple of Q's really - value & priority of having address lookups show incoming pending balances, and if I'm missing a straight forward approach (because otherwise I'm thinking whilst decoding a unconfirmed transaction is one thing, actually manipulating the state with transactions that aren't on the chain yet seems frought with potential pitfalls and probably needs some very careful consideration)

Thanks
Z

**Comment by dexX7** [comment]
You probably nailed it with:

> I'm thinking whilst decoding a unconfirmed transaction is one thing, actually manipulating the state with transactions that aren't on the chain yet seems frought with potential pitfalls and probably needs some very careful consideration

I believe at some point having full support for unconfirmed balances is a by-product, but at the very moment I don't really see how.

My post-0.0.10 plans were to investigate, whether we can move the plain transaction parsing one level deeper, i.e. integrate it into "the flow of unconfirmed transactions" of Core, in particular, because we'd then no longer need to fetch inputs from the DB (via `GetTransaction`), but rather have them directly available via "hot UTXO" access (via the coins view).

So the flow would then be:

1. transaction arrives
2. transaction passes the mempool
3. Core fires a transaction signal
4. We grap it and parse the transaction
5. The parsed transaction is stored in our DB

We can do this after 0.0.10, because then the transaction parsing is fully stateless, and it basically doesn't matter anymore, when we parse transactions. There are still a few issues: how do we handle the order of transactions in a block? etc.

If transactions are processed as soon as possible, and properly persisted, then we no longer need an enabled transaction index.

However, this is only one aspect, and a more tricky one is state and the execution of effects, which are (obviously) not stateless.

I'd love to hear your ideas about this, because I don't really see how we could tackle this. :)

One idea I've been playing with in my mind for some time: if we consider state as product of the execution of effects, and we have a way to describe all effects, then we may end up with something like (very schematically):

```c++
/**
 * Applies the effects on top of the given state snapshot.
 *
 * @param vEffects[in]  a collection of state modifications to apply
 * @param state[in,out] a representation of the state (i.e. balances, ...)
 */
void  GetStateFor(const std::vector<OmniEffect>& vEffects, OmniStateSnapshot& state)
{
    BOOST_FOREACH(const OmniEffect& effect, vEffects) {
        state.ApplyEffect(effect); // triggers/executes
    }
}
```

I'm not sure, if it's clear, where I'm going here, but instead of having a "global" state, we may have "state snapshots", which may be modified as we'd like. Say for example, we would like to reconstruct the state up until block 380000, then we'd create a blank state snapshot (because we start fresh), and "apply" all effects that there are until this block. Once a new block is processed, then we apply the effects from block 380001 "on top" of the state snapshot we constructed previously.

To handle unconfirmed transactions, we'd then have two snapshots of state: one for the confirmed state, and one, which is based on the confirmed state snapshot, namely the one for unconfirmed transactions. If somehow something changes, and the unconfirmed snapshot is no longer valid, then we could just clear it, create another copy of the confirmed state snapshot, and apply the unconfirmed effects once more.

**Comment by nixoid** [comment]
Ok, i see that request is not very simple to implement. But can we at least have omnichest api command to see all unconfirmed transactions for specific address? Otherwise there is no way for product that relies on omnichest api to calculate balance other than go through every network transaction.

**Comment by dexX7** [comment]
@nixoid: I think this is feasible.

How about something like:

---

#### omni_listpendingtransactions

Returns a list of unconfirmed Omni transactions, pending in the memory pool.

An optional filter can be provided to only include transactions which involve the given address.

Note: the validity of pending transactions is uncertain, and the state of the memory pool may change at any moment. It is recommended to check transactions after confirmation, and pending transactions should be considered as invalid.

See also:
- ["omni_gettransaction"](https://github.com/OmniLayer/omnicore/blob/omnicore-0.0.10/src/omnicore/doc/rpc-api.md#omni_gettransaction) *(supports unconfirmed transactions)*
- ["omni_listblocktransactions"](https://github.com/OmniLayer/omnicore/blob/omnicore-0.0.10/src/omnicore/doc/rpc-api.md#omni_listblocktransactions)

Arguments:

1. *address              (string, optional):* filter results by address (default: `"*"`, include any)

Result:

```js
[                       (array of string)
  "txid",                 (string) the hash of the pending transaction
  ...
]
```

Examples:

```bash
$ omnicore-cli "omni_listpendingtransactions"
$ omnicore-cli "omni_listpendingtransactions" "33E8LBtZWCpeS28AUkzdNDvPfwAiCpmYK6"
```

---

It's also thinkable to return the already parsed transactions, instead of their hashes, to skip using `"omni_gettransaction"` on the results, but this might as well be handled on the web API level (i.e. OmniChest).

Would this help?

**Comment by nixoid** [comment]
yep, should be good enough for us.
