### ISSUE TITLE
Exchange Testing 

### ISSUE THREAD

**Issue by Bitoy** [OmniLayer/omnicore#255]
When I posted
Buy 4 (SPT# 12) tokens for 0.25 MSC (total 1 MSC)

Sell Offer is 
2 @ 0.24
572 @ 0.25

I got 4.08 tokens for 1 MSC.   
This is fair but I was expecting to get only 4 tokens for 0.98 MSC?

**Comment by zathras-crypto** [comment]
Hey Bitoy!!!

Long time, how are you mate?

The "buy" (which is inverted into a sell) was 346329616bba4ddf897d9dfedec2b8a0eacbbed4d16033da74c195355d201661 I'm assuming?

I'll try and explain what's happening :)

At the time of the transaction, the MetaDEx for pair 12/1 looked like this:

```
0.24000000:mu9DKp1G99Bm1hBHXGjLCquhgg1cbM3vPj in 576214/021, txid: 503efc5828 , trade #12 2.00000000 for #1 0.48000000
0.25000000:mpZATHupfCLqet5N1YL48ByCM1ZBfddbGJ in 508478/076, txid: c7e626e9c1 , trade #12 650.00000000 for #1 162.50000000
0.35000000:mtg1B1Nca9a7xqsvNDqZLybHFSGFgTbqqb in 532545/009, txid: 7103a0e172 , trade #12 1.00000000 for #1 0.35000000
0.80000000:mpZATHupfCLqet5N1YL48ByCM1ZBfddbGJ in 524264/028, txid: 8b2820d61e , trade #12 100.00000000 for #1 80.00000000
```

You were offering to sell ```#1 1.0``` for ```#12 4.0``` (a price of 0.25).

* You were first partial matched against the best price (0.24) but there wasn't enough to match the entire trade so was only a partial fill, costing you ```#1 0.48``` and awarding you ```#12 2.0```.  
* Thus from your original selling of ```#1 1.0```, you still have ```#1 0.52``` left for sale.  
* You were then matched against the next best price (0.25) which sold your remaining ```#1 0.52``` for ```#12 2.08```.  
* Thus after the trade was completed, you end up with having sold your ```#1 1.0``` for ```#12 4.08```.

This looks like it was processed correctly - I think the issue is with the fact that all "buys" are actually sells, it's the amount for sale that gets filled.  If you got 4 tokens for 0.98 MSC as you note, there would still be a ```#1 0.02``` sell offer remaining on the exchange even though it still matched another trade.

```
zathras@zathras-desktop:~/github/build/omnicore$ src/omnicore-cli --testnet omni_gettrade 346329616bba4ddf897d9dfedec2b8a0eacbbed4d16033da74c195355d201661
{
    "txid" : "346329616bba4ddf897d9dfedec2b8a0eacbbed4d16033da74c195355d201661",
    "fee" : "0.00000268",
    "sendingaddress" : "mu9DKp1G99Bm1hBHXGjLCquhgg1cbM3vPj",
    "ismine" : false,
    "version" : 0,
    "type_int" : 25,
    "type" : "MetaDEx trade",
    "propertyidforsale" : 1,
    "propertyidforsaleisdivisible" : true,
    "amountforsale" : "1.00000000",
    "propertyiddesired" : 12,
    "propertyiddesiredisdivisible" : true,
    "amountdesired" : "4.00000000",
    "unitprice" : "0.25000000000000000000000000000000000000000000000000",
    "status" : "filled",
    "matches" : [
        {
            "txid" : "503efc582845bfdf0f9b2233b61004aedba636cbb81f902b22598b655a29dbd1",
            "block" : 576216,
            "address" : "mu9DKp1G99Bm1hBHXGjLCquhgg1cbM3vPj",
            "amountsold" : "0.48000000",
            "amountreceived" : "2.00000000"
        },
        {
            "txid" : "c7e626e9c1cc1662c0f13cadf60d4c4e67febf6bbf6f1a73c9534fd8ba498375",
            "block" : 576216,
            "address" : "mpZATHupfCLqet5N1YL48ByCM1ZBfddbGJ",
            "amountsold" : "0.52000000",
            "amountreceived" : "2.08000000"
        }
    ],
    "valid" : true,
    "blockhash" : "00000000000034c1478c158799ce16382b634807ec9a9a67f9e716b5d10d1e99",
    "blocktime" : 1444016563,
    "block" : 576216,
    "confirmations" : 436
}
```

Hope that makes sense mate, feel free to ask any questions :)  

Also FYI if you remove your log (```{bitcoindatadir}/testnet3/omnicore.log```) and then run with parameters ```--omnidebug=metadex1``` ```--omnidebug=metadex2``` ```--omnidebug=metadex3``` and ```--startclean``` you'll get a log file with a lot of data about what's going on, and it can show you how the trades are being matched and processed etc :)

**Comment by Bitoy** [comment]
Ok got it.  Omni Core team did a very good job!
