### ISSUE TITLE
BIP 70 payment request opens Send -> OmniLayer not Send -> Bitcoin

### ISSUE THREAD

**Issue by msgilligan** [OmniLayer/omnicore#311]
On Mac OS X, I have **Omni Core-Qt** set as my handler for BIP 70 payment links in my web browser. When I click on a BIP 70 link, **OmniCore-Qt** comes to the foreground and displays the **Send** tab/pane but displays the **Omni Layer** subpane rather than the **Bitcoin** subpane as would be expected.

(In the future we could implement an extension to BIP 70 for Omni currencies, and in that case a payment request for OMNI or USDT would in fact go to the **Omni Layer** subpane.)

Note: When I switched to the **Bitcoin** subpane, the correct info from the payment request was present.

**Comment by zathras-crypto** [comment]
Hey Sean,

The current UI is setup to remember the current tab selection (Omni or Bitcoin) when hitting the 'Send' page, and URIs simply trigger a switch to said Send page (since the handler knows nothing about the extra Omni tab).

Thus if you had the Bitcoin tab selected before hitting up a Bitcoin URI then the right tab should be used.  However if you had the Omni tab selected or did not have QT running then yep you're quite correct it'll open with the details populated in the correct place, but the Bitcoin tab won't be active.

I've pushed up a fix here https://github.com/OmniLayer/omnicore/pull/327 which from a quick bit of testing seems to do the trick.

Thanks for the report :)
