### ISSUE TITLE
Improve balance/fee threshold estimation

### ISSUE THREAD

**Issue by dexX7** [OmniLayer/omnicore#315]
Sometimes, when trying to send Omni, even though there is no "low balance" warning in the UI, then transactions don't go through and fail with `-211`, probably due to the coin selection, which results in transactions above the threshold.

We should improve the UI warning or raise the threshold for the warning.

**Comment by zathras-crypto** [comment]
I've tried to improve on this via https://github.com/OmniLayer/omnicore/pull/333 - I still don't think it's ideal  but since we can't know the size of some potential upcoming transaction until the user actually decides to transact, I think some degree of guesswork is inherent.

More than happy if you have better ideas dude, but otherwise I think this will be an improvement at least :)

**Comment by dexX7** [comment]
This is a pretty good approach in my opinion, I like it! Especially because it adjusts based on the actual confirm target.

**Comment by dexX7** [comment]
Resolved via #333. Awesome!

Side note, check this out @zathras-crypto: https://help.github.com/articles/closing-issues-via-commit-messages/
