### ISSUE TITLE
Send alerting to 0.0.9 clients

### ISSUE THREAD

**Issue by zathras-crypto** [OmniLayer/omnicore#323]
When the activation transactions are broadcast, we should also broadcast an 'old format' message to notify 0.0.9 clients of the upcoming features.

Note this will cause 0.0.9 clients without the ```-overrideforcedshutdown``` parameter to shut themselves down once the new features go live and they're thus out of consensus.

**Comment by dexX7** [comment]
Agreed. We should probably prepare them in advance to be ready.

There is one scenario I'm afraid of: let's assume the feature activation goes south for any reason, and we have to overwrite the activations and delay them, then the old alerts are still out. It's not necessary a bad thing, since users should upgrade anyway.

The alert should be sent after the activations confirmed, to avoid we miss the signing window and it ends up to be a false alarm.

Currently our window is 1167 blocks until the 2 weeks grace period kicks in, which is roughly 5-8 days.

**Comment by dexX7** [comment]
Only 2034 blocks left until the activation of feature id 4, and 2534 blocks left for the others.

I think we should a) post to the mailing list, b) ideally publish a blog post, c) probably start with the alerts. What do you think?

**Comment by dexX7** [comment]
You sent me the following payload:
```
ffffffff343a3339343530303a343a303a4d617374657220436f726520302e302e3920697320646570726563617465642c20706c65617365207570677261646520746f204f6d6e6920436f726520302e302e31302e7820617420646f776e6c6f61642e6f6d6e696c617965722e6f72672e20205468697320636c69656e742077696c6c206e6f206c6f6e67657220626520757361626c6520616674657220626c6f636b203339343530302e00
```

... which translates to:
```
version: 65535 (alert)
type: 65535 (alert)
text: 4:394500:4:0:Master Core 0.0.9 is deprecated, please upgrade to Omni Core 0.0.10.x at download.omnilayer.org.  This client will no longer be usable after block 394500.
```

... further broken down:
```
alert type: 4 (check transaction support)
expiry value: 394500 (block height)
type check: 4 (transaction type)
version check: 0 (transaction version)
```

Looks good to me!

**Comment by dexX7** [comment]
Done:

ffee7a9026a22173a53edc8680e26570e971ffae7c2aa173d26f41648e579946
