### ISSUE TITLE
Remove requirements when creating raw payload

### ISSUE THREAD

**Issue by dexX7** [OmniLayer/omnicore#417]
When creating raw payloads, there shouldn't be requirements such as requiring that a property exists, to allow creating payloads even with an unsychronized client.

Via https://github.com/OmniLayer/omniwallet/issues/1314#issuecomment-239715137

**Comment by zathras-crypto** [comment]
Hey @dexX7 I started looking at this change (eg https://github.com/zathras-crypto/omnicore/commit/1fb73b5387349e24b23bbd2c3f3fa161c7cd9fef) but it's actually not as simple as it sounds to just remove the state checks.  We use the divisibility of the property to determine how we parse the amount field - this wouldn't work with an unsynced client because it doesn't know the property type for a transaction it hasn't seen yet, so doesn't know how to parse the amount.

**Comment by dexX7** [comment]
> this wouldn't work with an unsynced client because it doesn't know the property type for a transaction it hasn't seen yet, so doesn't know how to parse the amount

Argh, I see. We could fall back to a default parsing route, e.g. treat unknown amounts as divisible. This is also the default of [isPropertyDivisible](https://github.com/zathras-crypto/omnicore/blob/1fb73b5387349e24b23bbd2c3f3fa161c7cd9fef/src/omnicore/sp.cpp#L565). There should be a note in the description/API documentation though.

**Comment by dexX7** [comment]
Resolved via #567.
