### ISSUE TITLE
Synchronizing with testnet is very slow

### ISSUE THREAD

**Issue by congnghiakhiem** [OmniLayer/omnicore#519]
I install omnicore for testing. But it is very slow to synchronize with the network. It is synchronizing for 5 days and keeps synchronizing now. It is connected with 8 peers and ping time is arround 200 ms. Because of slowly synchronizing, I can not test to send and receive TBTC to my wallet. Please help me.

**Comment by qld-cf** [comment]
same question

**Comment by qld-cf** [comment]
somebody help us😢

**Comment by terryzhouyl** [comment]
me too. I has spent 4 days synchronizing. the block num is still around 770000 , the synchronzing speed is around 1kb. now, i can do nothing but wait the block synchronzing.

**Comment by dexX7** [comment]
Hey guys,

unfortunately there is nothing we can do. My guess is that this is because there is another testnet for SW and the old one isn't really used anymore.

If you want to do tests, I'd recommend to use regtestnet by running Omni Core with `-regtest=1`. This creates a private network, where you can mine blocks yourself with `generate n` where `n` specifies the number of blocks to mine. This is also a lot faster than testing on testnet. :)

**Comment by dexX7** [comment]
Please feel free to reopen this issue or create a new one, if you have another question.

**Comment by izzycoder18** [comment]
It's been 2 weeks and neither testnet nor mainnet have completed the network sync. Considering that I use a very fast network and that Bitcoin core wallet synchronized in less than 24 hours, is there any issue with the omni wallets? 
Any idea why the wallet basically does not work?
