### ISSUE TITLE
I offer pay to help me or tell me how to recover my USDT

### ISSUE THREAD

**Issue by josegalicia** [OmniLayer/omnicore#538]
Good morning.
I have a problem with my transaction, I sent USDT (Tether) to my bitcoin address because I thought I could, but obviously not and I would like to get my money back. On the platform I use bitcoin as if I really had it but it is not reflected in my wallet.

I hope you can help me with my problem and give me a solution.
 
Thank you.

Bellow is confirmation e-mail you sent.
 
![confirmacion](https://user-images.githubusercontent.com/35533692/35049971-49d2bd48-fb67-11e7-91f4-7fc31e066115.png)
![fail address](https://user-images.githubusercontent.com/35533692/35049972-49eb7892-fb67-11e7-8409-a8a552a17844.PNG)
![fail](https://user-images.githubusercontent.com/35533692/35049973-4a053818-fb67-11e7-951e-aecf641d9cad.png)
![usdt tetherus](https://user-images.githubusercontent.com/35533692/35049974-4a1d17ee-fb67-11e7-86c2-d435af095fef.png)

**Comment by dexX7** [comment]
Hi there,

you need an Omni aware wallet to transfer Tether.  Please reach out to the Binance support. In theory they should be able to retrieve the funds.

**Comment by martyer1949** [comment]
I also suffered a similar loss for the same reason. I SUGGEST A CLASS ACTION LAW SUIT! They obviously know how to get the USDT into your Bitcoin wallet because they sent you a tiny bit of what they should have sent you. THIS IS CRIMINAL!

**Comment by dexX7** [comment]
@martyer1949: I understand your frustration, but please don't post the same message all over this repository. This is neither a support channel for Binance, nor for Coins.ph, but a repository to discuss development of Omni Core.

**Comment by dexX7** [comment]
Please let us know how it went. Until then, I'm going to close this issue, because there is nothing we can do as developers.

**Comment by Amin1214** [comment]
same my problem pls help me

**Comment by martyer1949** [comment]
I believe a law suit is the only way. We should sue coins.ph together. In America it is called a class action law suit.
--------------------------------------------
On Tue, 6/5/18, Amin1214 <notifications@github.com> wrote:

 Subject: Re: [OmniLayer/omnicore] I offer pay to help me or tell me how to recover my USDT (#538)
 To: "OmniLayer/omnicore" <omnicore@noreply.github.com>
 Cc: "martyer1949" <martyer1949@yahoo.com>, "Mention" <mention@noreply.github.com>
 Date: Tuesday, June 5, 2018, 9:59 AM
 
 same my problem pls help me
 
 —
 You are receiving this because you were mentioned.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by dexX7** [comment]
Hi guys, please see:

https://github.com/OmniLayer/omnicore/wiki/I-sent-tokens-to-an-incompatible-wallet-such-as-Coinbase-or-GDAX.-Can-you-reverse-the-transaction%3F
