### ISSUE TITLE
Propertyid of USDT in omnicore

### ISSUE THREAD

**Issue by khaitranvan96kt** [OmniLayer/omnicore#545]
I see omnicore has USDT support but i do not know its propertyid. Did I find out if it was TetherUS and had the propertyid = 31?

**Comment by dexX7** [comment]
Yes, USDT/TetherUS has the property identifier 31.

**Comment by kazaff** [comment]
@dexX7 
What about 192,330 and 341? 
I found them on [office assets page](https://www.omniwallet.org/explorer/assets)

**Comment by dexX7** [comment]
Hi @kazaff,

tokens are identified by their identifier, not by their name, and people can freely create as many "TetherUS" tokens as they want.

**Comment by harrymaurya05** [comment]
Hello, I'm new in omnicore client but as I understand 31 property identifer is assign for Usdt (tether) but
when i execute this command "omnicore-cli "omni_getproperty" 31"  i'm getting this as a result 
"
{
  "propertyid": 31,
  "name": "tokenmagic.com",
  "category": "TOKENMAGIC",
  "subcategory": "TOKENMAGIC",
  "data": "",
  "url": "Beeswax",
  "divisible": false,
  "issuer": "mrAVAPxdQEZxFkunh56skB6sgJa6vrfrpo",
  "creationtxid": "9588ab12ef040767b1e9fe4181e294409da6cab9792f89ccc55bc621b47e2563",
  "fixedissuance": true,
  "managedissuance": false,
  "totaltokens": "80000"
}
" 
if 31 is for tether then why 31 show tokenmagic.com instead of tether.to

**Comment by harrymaurya05** [comment]
@santos177 
Thanks

**Comment by harrymaurya05** [comment]
@santos177
 I have a question regarding token transfer using omni core client.
suppose I have 20 usdt in one address which is generated by omnicore , now if i want to transfer 10 usdt from one address to another address which also generated by omnicore. so command should look like this right  " omnicore-cli "omni_funded_send" "1DFa5bT6KMEr6ta29QJouainsjaNBsJQhH" \
    "15cWrfuvMxyxGst2FisrQcvcpF48x6sXoH" 1 "10.0" "
