### ISSUE TITLE
USDT Coins sent from Binance to Kraken stuck at Omni

### ISSUE THREAD

**Issue by pklcbnq** [OmniLayer/omnicore#572]
Transaction made on 2/17/18. Transaction ID https://omniexplorer.info/lookuptx.aspx?txid=49fe0ccbb92f07e35ab493ab4266a0a016e030c3b84826323eef542c0ac82dae.

Can you help?

**Comment by dexX7** [comment]
Hi there,

unfortunately there is nothing we can do as developers, except facilitating the process and pointing in the right direction.

Kraken is an exchange, which supports USDT, but I assume you sent the tokens to your Bitcoin address instead of an USDT wallet? They should be able to help you in this case, so please contact the Kraken support.

**Comment by dexX7** [comment]
I added a wiki page about this topic. Please let me know, if there is still anything unclear:

- [FAQ: I sent tokens to an incompatible wallet such as Coinbase or GDAX. Can you reverse the transaction?](https://github.com/OmniLayer/omnicore/wiki/I-sent-tokens-to-an-incompatible-wallet-such-as-Coinbase-or-GDAX.-Can-you-reverse-the-transaction%3F)

Please also feel free to reopen this issue, if there is any progress. We'd also love to hear, if you were able to retrieve the tokens!
