### ISSUE TITLE
questions about account and address in omni layer

### ISSUE THREAD

**Issue by karokarolee** [OmniLayer/omnicore#574]
Hi,
From the GUI of omni core, in menu "Receiving Addresses...", I got three addresses and edited Label names for them.  If I operated in GUI to send bitcoin to the address "moneyqMan7uh8FqdCA2BV5yZ8qVrc9ikLP", some omni coins will be sent to my corresponding address, but if I send bitcoin to "moneyqMan7uh8FqdCA2BV5yZ8qVrc9ikLP" through rpc api, like "sendtoaddress" and "sendfrom", omni coins will be sent back to some new addresses with none label. And when I tried to transfer omni coin from those new addresses to my named (with label) address, transaction will fail possible due to no bitcoin in those addresses.
I am confused, it seems no way to specify address to receive omni coins when send bitcoin to "moneyqMan7uh8FqdCA2BV5yZ8qVrc9ikLP" through rpc api. 
And, I have no clear idea about concepts "sending addresses", "receiving addresses" and "accounts". Per my understanding, every address should can both send and receive bitcoins and omni layer tokens, is it correct?

**Comment by dexX7** [comment]
The sender of an Omni transaction is determined by the first input of the transaction. If you send bitcoins from address A to moneyqMan7uh8FqdCA2BV5yZ8qVrc9ikLP, then A should get the tokens. It could be that sendtoaddress uses an unrelated address. As a tip, you can turn on coin control and then manually select coins to send in the bitcoin sending tab.

When sending Omni Layer tokens, the address sending needs to have some bitcoins, because OL transactions are Bitcoin transactions.

The accounts concept of Bitcoin and Omni Core is somewhat flawed and you better use something else to keep track of coins.

> Per my understanding, every address should can both send and receive bitcoins and omni layer tokens, is it correct?

Yes. :)

Please let me know, if this helps.

**Comment by dexX7** [comment]
Please feel free to reopen this issue, if you have new information to provide.
