### ISSUE TITLE
How to send USDT from transit address to main address?

### ISSUE THREAD

**Issue by dchetverikov** [OmniLayer/omnicore#589]
Hello.

We are implementing Tether currency (propertyId = 31) on our e-currencies exchange web-site.

The problem is as follows:

In order to link specific user with his USDT transaction we generate new address for every exchange operation and ask user to send his USDT to this new address. Suppose, he is to send us 100 USDT. After transaction is complete we will have 100 USDT and 0.00000546 BTC on our newly generated address.

After that we need to consolidate USDTs sent by our clients on one consolidated address. But we can not send USDTs from generated addresses to our consolidated address since there are not enough BTCs on those addresses to pay transfer commission fee to miners.

Please, advise what is the best way to solve the issue?

**Comment by hhy464591454** [comment]
@dchetverikov  Hey, the old address sent USDT to the new address also needs to pay TBC; if the 100 USDT transaction costs are 0.001BTC, sent from the old address to the new address, where does the transaction cost come from? Do you buy it?

**Comment by hhy464591454** [comment]
@dchetverikov  As for the above, I also encountered similar problems, please solve it, thank you, thank you.

**Comment by dexX7** [comment]
@dchetverikov: there is no handy way to do this, but you can pay the Bitcoin transaction fees from different sources than the one where you send the tokens from.

The first input of the transaction determines the token sender. In your case you'd use the 0.00000546 BTC output for the transaction and then add other inputs for the fees.

For the manual transaction creation, check out the following wiki guide:

https://github.com/OmniLayer/omnicore/wiki/Use-the-raw-transaction-API-to-create-a-Simple-Send-transaction

Instead of using a single UTXO in step three, you could try to use multiple ones.

**Comment by wanglei-sky** [comment]
Can I send a transaction to an address with output from different addresses? @dexX7

**Comment by vae520283995** [comment]
@dchetverikov 
Is it solved? I also want to implement this function. Please tell me, thank you

**Comment by dexX7** [comment]
@wanglei-sky:

the first input must come from the source that holds the token, all other inputs can be from different addresses, but you need a tiny bit from the token source.

**Comment by sgrmoharil** [comment]
Hi @dexX7, omni_funded_send is showing invalid method on Omni Core Wallet 0.3.0. Please help

**Comment by dexX7** [comment]
Please let me know, if you need more help. Until then, I'm going to close this issue.
