### ISSUE TITLE
selected inputs for the send transaction

### ISSUE THREAD

**Issue by macrotea** [OmniLayer/omnicore#609]
Hello, I also have the same problem.

Omni_send 1h4f8BfWBmZoDDmtLXdPcs3DbkRpbFYjG 1F3kKH4buPodMK49Rm1QcAracQSbsusx4e 310.1

Remind me:

Error with selected inputs for the send transaction (code -206)

But I pass the tx:

The account corresponding to 1h4f8BfWBmZoDDmtLXdPcs3DbkRpbFYjG is:

349e5568-4f18-462e-8581-08fec1974881

The account corresponding to 1F3kKH4buPodMK49Rm1QcAracQSbsusx4e is:

C8b0145a-0a90-4143-bfc8-a7e6ae54744f

However, when I check the BTC balance of the two account,

349e5568-4f18-462e-8581-08fec1974881

Btc:0.00101638

C8b0145a-0a90-4143-bfc8-a7e6ae54744f

Btc:0

therefore

1h4f8BfWBmZoDDmtLXdPcs3DbkRpbFYjG should have enough BTC to send this usdt transaction.

But why is it a failure? Consult! Thanks!!!

the getinfo cmd show me >

{
"version": 130200,
"protocolversion": 70015,
"walletversion": 130000,
"balance": 0.00100546,
"blocks": 522213,
"timeoffset": 0,
"connections": 8,
"proxy": "",
"difficulty": 4143878474754.188,
"testnet": false,
"keypoololdest": 1525618904,
"keypoolsize": 10001,
"unlocked_until": 0,
"paytxfee": 0.00000000,
"relayfee": 0.00001000,
"errors": ""
}

**Comment by macrotea** [comment]
@msgilligan @germanf @marvgmail @dexX7 @CraigSellars 
help

**Comment by timka-zhm** [comment]
@macrotea it's weird that you have just `522213` blocks... Has your synchronization been finished?

**Comment by timka-zhm** [comment]
@macrotea Do you really need *TWO* issues?
https://github.com/OmniLayer/omnicore/issues/608

**Comment by macrotea** [comment]
Hello, I saw through Omni wallet that I have completed the synchronization. When I execute the getinfo command, the message I see is:
{
"Version": 130200,
"Protocolversion": 70015,
"Walletversion": 130000,
"Balance": 0.00100546,
"Blocks": 522638,
"Timeoffset": 0,
"Connections": 8,
"Proxy": "",
"Difficulty": 4143878474754.188,
"Testnet": false,
"Keypoololdest": 1525618904,
"Keypoolsize": 10001,
"Unlocked_until": 1626293000,
"Paytxfee": 0,
"Relayfee": 0.00001000,
"Errors": ""
}
When I execute the getblockchain command:
{
"Chain": "main",
"Blocks": 522638,
"Headers": 522638,
"Bestblockhash": "0000000000000000003800bf532c4f1d6668e38497c5a5ef838c9950085e9350".
"Difficulty": 4143878474754.188,
"Mediantime": 1526296513,
"Verificationprogress": 0.9999954245054155,
"Chainwork": "000000000000000000000000000000000000000001be836ee22b0c3ee2a3391e".
"Pruned": false,
"Softforks": [
{
"Id": "bip34",
"Version": 2,
"Enforce": {
"Status": true,
"Found": 1000,
"Required": 750,
"Window": 1000
},
"Reject": {
"Status": true,
"Found": 1000,
"Required": 950,
"Window": 1000
}
},
{
"Id": "bip66",
"Version": 3,
"Enforce": {
"Status": true,
"Found": 1000,
"Required": 750,
"Window": 1000
},
"Reject": {
"Status": true,
"Found": 1000,
"Required": 950,
"Window": 1000
}
},
{
"Id": "bip65",
"Version": 4,
"Enforce": {
"Status": true,
"Found": 1000,
"Required": 750,
"Window": 1000
},
"Reject": {
"Status": true,
"Found": 1000,
"Required": 950,
"Window": 1000
}
}
]
"Bip9_softforks": {
"CSV": {
"Status": "active",
"StartTime": 1462060800,
"Timeout": 1493596800
},
"Segwit": {
"Status": "active",
"StartTime": 1479168000,
"Timeout": 1510704000
}
}
}
I did send issue two times, because I don't know which item you will reply to me.
But I do have problems now. I don't know how to solve this problem. I hope you can get help.

**Comment by macrotea** [comment]
@timka-zhm 
What do you usually use to communicate and chat tools, I want to add your friends, so that it is better to promote communication on this issue, if you help me solve the problem, I would like to pay you 0.5 eth, after all, my boss urged me to solve it as soon as possible!

**Comment by timka-zhm** [comment]
Once, but in Testnet, I got the same error during `omni_send` method.
I had enough(as I thought) funds in BTC. 
After I added more BTC(about 0.5) I got the success.
I think this problem related to the balance. So I suggest you, if you can, increase BTC balance on the sender address. It worked for me

**Comment by timka-zhm** [comment]
@macrotea , One more

`omni_send 1h4f8BfWBmZoDDmtLXdPcs3DbkRpbFYjG 1F3kKH4buPodMK49Rm1QcAracQSbsusx4e 310.1` - method `omni_send` requires third parameter a property id, in case of OMNI coin you need to set `1`.
`omni_send 1h4f8BfWBmZoDDmtLXdPcs3DbkRpbFYjG 1F3kKH4buPodMK49Rm1QcAracQSbsusx4e 1 310.1` - try this

**Comment by dexX7** [comment]
Hi @macrotea, you need some BTC for Omni transactions, see:

https://github.com/OmniLayer/omnicore/wiki/Why-do-I-need-bitcoin-to-create-Omni-transactions%3F

Depending on the transaction you were trying to send, you might not have enough BTC to cover the fees for the transaction.

**Comment by timka-zhm** [comment]
@dexX7 , Could you kindly tell me how many BTC do I need to send OMNI successfully?

`{"result":{"balance":"1.50000000","reserved":"0.00000000"},"error":null,"id":"omni_test"}` - `mgdzYzPxWoZX77ookWkKmnDeGdELxkKLAN` OMNI balance

`{"result":[[["mgdzYzPxWoZX77ookWkKmnDeGdELxkKLAN",0.00009546,"3-52"]]],"error":null,"id":"omni_test"}` - BTC balance

Is it not enough `0.00009546` BTC to send `1.5` OMNI?
According to https://live.blockcypher.com/btc-testnet/tx/460189e33978d716ad9c084e627e5d136b0e9735d2bb0cb53e5fa2340bb30693/ transaction fee `0.00000919 BTC` - this is less then I have.

Thanks!

**Comment by dexX7** [comment]
Hey @timka-zhm, it really depends on your local fee settings. You could start Omni Core with the `-txconfirmtarget=n` setting and use a high n like 25, to use a really low fee.

**Comment by burnside** [comment]
@dexX7 - I've been working with omnicore on testnet today and ran into the "Error with selected inputs for the send transaction" issue as well.  My initial test flow was:

- install software, start it up on testnet, wait for it to sync up
- generate an address (Address1) and send 0.01 testnet coins to it from a faucet
- send 0.0001 testnet coins from Address1 to address "moneyqMan7uh8FqdCA2BV5yZ8qVrc9ikLP", received back 0.01 of both propertyid 1 & 2 and was left with one utxo of 0.00989767 with what I assume to be a refund address attached, as the address does not show up in my address list.
- generate another address (Address2) and try to omni_send 0.0001 of propertyid 2 from Address1 to Address2.  Then get the selected inputs error.

At this point I did a bunch of looking into getbalance, my fee settings, and your above suggested txconfirmtarget setting.  None of my configuration tweaking fixed it.

Finally I decided to try sending my single unspent output from the refund address to Address1.  After doing this, my listunspent showed my single utxo WITH Address1.  Subsequently, the exact same omni_send that failed initially went through successfully.

Does omnicore expect there to be utxo's expressly attached to the "from" addresses in order to originate omni transactions?

**Comment by dexX7** [comment]
Hi @burnside,

this is indeed correct. The token sender is determined based on the first transaction input. Here are some examples: https://github.com/OmniLayer/omnicore/issues/595#issuecomment-383466222

Something like #388 is an often requested feature and we are looking to integrate a simple version of it for the next release.

**Comment by burnside** [comment]
@dexX7 thank you, appreciate the reply.

You've probably already thought of all of this, but here are some potential implementation thoughts, coming from an exchange operations perspective:

Given that the first input is how Omni must determine the sender, and given that it's a PITA to manually maintain a few satoshis in each account with a balance, you could batch transactions under the hood when necessary.

- Check fromaccount for utxo's capable of sending the transaction.
- If there are none, search the utxo's for an input not currently attached to an omni address with an omni balance. (will be fairly common if the user has done any core non-omni transactions due to the random change addresses)
- If it finds one, generate two transactions - first a minimal deposit to the fromaccount, then the requested omni send.
- If it does not find one, then "borrow" the largest value utxo from an omni account, generate a minimal deposit to the fromaccount, then generate the omni send.

There's not really any additional transaction costs with this setup, it's all transactions you'd have to do manually anyway?

Thinking from a mass deposit/sweep to cold wallet scenario - The other thing that I think would be be a great option/flag is automatic minimum balance management.  Eg: When spending the remaining balance of an omni account, rather than the change coming back to the empty account you could automatically split the change across multiple omni accounts that hold some omni, but have sub-optimal bitcoins attached.  Batching the split and anticipating future transactions will save transaction counts and fees going forward.  You could prioritize by omni balance or something and have some configurable fixed target amount to keep attached to all of the wallets.

I'm pretty sure I'll be doing most of this via raw transactions in my exchange implementation, but it'd definitely be good for omni adoption if this could all be automated under the hood.

**Comment by songjim** [comment]
HI，guys，
when i run omni_sendissuancecrowdsale "mmDnDrLnzvezEhSumN5zXEiM1Gxx8gagbB" 2 1 0 "song22" "songjian22" "SJ22" "" "" 2 "100" 1529055817 30 2 on regtest  then i get Error with selected inputs for the send transaction (code -206) . can anyone help me?
this address 'mmDnDrLnzvezEhSumN5zXEiM1Gxx8gagbB' has 20 balance

**Comment by dexX7** [comment]
@songjim: you need some BTC to send the transaction.

**Comment by dexX7** [comment]
@burnside: I pushed https://github.com/OmniLayer/omnicore/pull/658, which provides two new RPCs for "funded sending". The idea is that, if an exchange wants to move incoming funds, they usually want to sweep all tokens and as well as all BTC, so there is no leftover. The new RPCs select all BTC from the specified sender and take the missing amount, if there is still one, from a specified fee source.

Does this help your use case?

**Comment by nanmu42** [comment]
The sweeping function would be really helpful, looking forward to it.

**Comment by burnside** [comment]
@dexX7 This is great, I am looking forward to adapting my implementation accordingly!

**Comment by dexX7** [comment]
Awesome @burnside, let me know how it goes.
