### ISSUE TITLE
Update your docs for testnet section

### ISSUE THREAD

**Issue by rockandruby** [OmniLayer/omnicore#842]
As for me some details of getting TOMNI are still unclear(and as google shows not just for me). Steps I do
1. Deposit account(doesn't matter what btc address I use because I have no ability to choose address 'from',  when use sendtoaddress method)
2. I use sendtoaddress to moneyqMan7uh8FqdCA2BV5yZ8qVrc9ikLP.
3. I receive some TOMNI.
Yes, acctually I receive tomni, my wallet is credited but some random address receives this tomni and not a particular address. So my question is - Is that the right case? For example, I want to get tomni on address mxpjTJy7Pv9pi64XxQ2H7TQuSiDU8XKjER, what I do now -  I search for address that was credited with tomni and then send them to  mxpjTJy7Pv9pi64XxQ2H7TQuSiDU8XKjER.
So it would be great if u add more details about tesnet usage.

**Comment by dexX7** [comment]
Hello there,

you are correct. You received the TOMNI at a random address, because `sendtoaddress` just uses a random address with BTC in it for the send.

You could either then forward the TOMNI to the actual destination (e.g. with `omni_send`), or you may create a raw transaction, which spends BTC from the actual source you'd like to use (e.g. with `listunspent` to list unspent outputs, create a raw transaction with `createrawtransaction`, then sign it with `signrawtransaction` and finally send it with `sendrawtransaction`).
