### ISSUE TITLE
Omnicore replace bitcoin core

### ISSUE THREAD

**Issue by lealife** [OmniLayer/omnicore#858]
I have run `bitcoind` 0.12.1 and full synced. Can i run `omnicored` to replace `bitcoind` and use the same datadir ?

**Comment by dexX7** [comment]
Hello, this should work, yes. Here are the specifics:

---

Omni Core is based on Bitcoin Core 0.13.2 and can be used as replacement for Bitcoin Core. Switching between Omni Core and Bitcoin Core may be supported.

Upgrading to a higher Bitcoin Core version is generally supported, but when downgrading from Bitcoin Core 0.15, Omni Core needs to be started with -reindex-chainstate flag, to rebuild the chainstate data structures in a compatible format.

Downgrading to a Bitcoin Core version prior to 0.12 may not be supported due to the obfuscation of the blockchain database. In this case the database also needs to be rebuilt by starting Omni Core with -reindex-chainstate flag.

Downgrading to a Bitcoin Core version prior to 0.10 is not supported due to the new headers-first synchronization.
